.\" Manpage for vished.
.TH man 8 "07 Oct 2018" "1.0" "vished man page"
.SH NAME
nuseradd \- create a new LDAP user 
.SH SYNOPSIS
vished [FILENANE]
.SH DESCRIPTION
Combine shell file creation, x user permission creation and launces vi.
.SH OPTIONS
No options yet. Future versions may support different file extensions and or editors.
.SH SEE ALSO
vi(?),chmod(?)
.SH BUGS
No known bugs.
.SH AUTHOR
dhelle2@uic.edu (original author bmiddha)
